---
title: "Constructing PGLS dataset for CCA species with functional and life-history trait data"
author: "Anne-Cecile Colin"
date: "10/06/2021"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(devtools)
library(readr)
library(sp)
library(raster)
library(stats)
library(plyr)
library(dplyr)
library(readxl)
library(ggplot2)
library(conflicted)
```

## Merging life-history trait data to CCA# by = species

``` {r adding life-history data}

CCAnumber <- read.csv("../data/life_history_CCA.csv", header = T)
view(CCAnumber)
nrow(CCAnumber)

species <- read.csv("../data/CCA_VPM_species_PGLS.csv", header = T) %>%
  distinct(acceptedname_ala, .keep_all = TRUE)
colnames(species)[4] <- "name"
nrow(species)
view(species)

trait.ds <- left_join(species, CCAnumber, by = "name") %>%
  distinct(name, .keep_all = T) #%>%
  drop_na(genus)


view(trait.ds)  
nrow(trait.ds)

write.csv(trait.ds, "../outputs/") # add file name
```

## Merging 