---
title: "Cleaning the dubious taxonomy from the PGLS dataset"
author: "Anne-Cecile Colin"
date: "10/06/2021"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Aim:

In the previous script `1_constructing_PGLS_datasets.Rmd`, I merged and cleaned the life-history traits from EUCLID with Victoria's CCA dataset.

The aim of this script is to use the datasets created from `1_constructing_PGLS_datasets.Rmd` to figure out the best match for taxa names across the three datasets: the list of taxa from Thornhill's phylogeny, the taxa at CCA that Victoria uses for her analysis, and the taxa specified in the EUCLID flora.

The descriptions in the EUCLID flora can be pretty old and therefore outdated in terms of taxonomy (what names the taxa are refered to as).
With this script I will make a list of the unmatched taxa across the three datasets and update the taxa names in my EUCLID dataset so they can all match to their current taxonomical name.

At the end of this script I will have a different lists of unmatched taxa among the three datasets. I will use those lists to count the number of dubious species in the EUCLID dataset with Dean, and change the taxa name according to the classification of Eucalypts. 
